#!/bin/bash
#
# Bash Template Script Generator
# Generates a Bash Script Template that handles Arguments and Flags Cleanly
#
# @author: Will Salemé <william.saleme@gmail.com>
# @license: GNU v3
# @date: March 12, 2016
##

# Fetch the Bash Script Template
SCRIPT_TEMPLATE=$(curl -Ls http://bit.ly/bash-script-template)

# TODO: Replace tokens here to enable template customization
#...

# Output the Template
printf "%s" "${SCRIPT_TEMPLATE}"
